
paths:
  /api/v1/auth/signup:
    post:
      summary: Register a new users.
      tags:
        - 🔐 User Authentication
      description: This Api endpoint allow users to register or signup to create their account .
      operationId: register
      requestBody:
        description: User registration details
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                  example: "userOne"
                email:
                  type: string
                  example: "one@gmail.com"
                password:
                  type: string
                  example: "Staging123$"
      responses:
        '201':
          description: User registered successfully.
          headers:
            Access-Control-Allow-Credentials:
              schema:
                type: string
                example: "true"
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: "*"
            Connection:
              schema:
                type: string
                example: "keep-alive"
            Content-Length:
              schema:
                type: string
                example: "500"
            Content-Type:
              schema:
                type: string
                example: "application/json; charset=utf-8"
            Date:
              schema:
                type: string
                example: "Sun, 12 Dec 2021 06:25:37 GMT"
            ETag:
              schema:
                type: string
                example: W/"1f4-1q2mEjJRVbcL1EjonLxprbS85erA4qcFg"
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
            Rate-Limit:
              schema:
                type: string
                example: "500"
            Rate-Limit-Remaining:
              schema:
                type: string
                example: "495"
            RateLimit-Reset:
              schema:
                type: string
                example:  '772'
            X-Powered-By:
              schema:
                type: string
                example:  Express
          content:
            application/json:
              schema: 
                type: object
                properties:
                  success:
                    type: boolean
                    example:  true
                  message:
                    type: string
                    example: "User created successfully"
                  data:
                    type: object
                    properties:
                      userName:
                        type: string
                        exaple: "userOne"
                      email:
                        type: string
                        example:  "one@gmail.com"
                      avatar:
                        type: string
                        example: "https://api.dicebear.com/6.x/pixel-art/svg?seed=userOne&background=%23000000&radius=50&colorful=1"
                      password:
                        type: string
                        example: "$2a$120$xzvagjt.G1mtcSViSCQYK.Fj0pFr5i6wRbEEIJD2hYRgZeuX/A3iv8Lu."
                      roles:
                        type: string
                        example: "User"
                      onboarded:
                        type: boolean
                        example: false
                      isEmailVerified:
                        type: bollean
                        example: false
                      refreshToken:
                        type: string 
                        example: ''
                      _id:
                        type: string
                        example: "6576ab6110a2a0e5b125600c"
                      createdAt:
                        type: string
                        example: "2023-12-11T06:25:37.609Z"
                      updatedAt:
                        type: string
                        example: "2023-12-11T06:25:37.609Z"
                      __v:
                        type: string
                        example: 0
  
  /api/v1/auth/login:
    post:
      summary: Login a user 
      tags:
          - 🔐 User Authentication
      description: This Api endpoint allow users to login to their account .
      operationId: login
      requestBody:
        description: User login details
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "one@gmail.com"
                password:
                  type: string
                  example: "Staging123$"
      responses:
        '200':
          description: User logged in successfully.
          headers:
            Access-Control-Allow-Credentials:
              schema:
                type: string
                example: "true"
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: "*"
            Connection:
              schema:
                type: string
                example: "keep-alive"
            Content-Length:
              schema:
                type: string
                example: "500"
            Content-Type:
              schema:
                type: string
                example: "application/json; charset=utf-8"
            Date:
              schema:
                type: string
                example: "Sun, 12 Dec 2021 06:25:37 GMT"
            ETag:
              schema:
                type: string
                example: W/"1f4-1q2mEjJRVbcL1EjonLxprbS85erA4qcFg"
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
            Rate-Limit:
              schema:
                type: string
                example: "500"
            Rate-Limit-Remaining:
              schema:
                type: string
                example: "495"
            RateLimit-Reset:
              schema:
                type: string
                example:  '772'
            X-Powered-By:
              schema:
                type: string
                example:  Express
          content:
            application/json:
              schema: 
                type: object
                properties:
                  success:
                    type: boolean
                    example:  true
                  message:
                    type: string
                    example: "User logged in successfully"
                  data:
                    type: object
                    properties:
                      userName:
                        type: string
                        exaple: "userOne"
                      email:
                        type: string
                        example: "one@gmail.com"
            